class BookWordModel {
  String occurence;
  String id;
  String title;
  String authorsName;
  String authorBirthYear;
  String authorDeathYear;
  String subject0;
  String subject1;
  String subject2;
  String subject3;
  String subject4;
  String subject5;
  String subject6;
  String subject7;
  String subject8;
  String subject9;
  String subject10;
  String bookshelve0;
  String bookshelve1;
  String bookshelve2;
  String bookshelve3;
  String language;
  String copyright;
  String mediaType;
  String coverImage;
  String textBook;
  String downloadCount;
  String translatorName;
  String translatorBirthYear;
  String translatorDeathYear;

  BookWordModel({
    required this.occurence,
    required this.id,
    required this.title,
    required this.authorsName,
    required this.authorBirthYear,
    required this.authorDeathYear,
    required this.subject0,
    required this.subject1,
    required this.subject2,
    required this.subject3,
    required this.subject4,
    required this.subject5,
    required this.subject6,
    required this.subject7,
    required this.subject8,
    required this.subject9,
    required this.subject10,
    required this.bookshelve0,
    required this.bookshelve1,
    required this.bookshelve2,
    required this.bookshelve3,
    required this.language,
    required this.copyright,
    required this.mediaType,
    required this.coverImage,
    required this.textBook,
    required this.downloadCount,
    required this.translatorName,
    required this.translatorBirthYear,
    required this.translatorDeathYear,
  });
}
